oprofile: lower priority for version 1.1.0
I can't get do_configure to work. It fails with

checking /mnt/xfs/devel/pil/oe-lite/tmp/work/machine/arm-cortexa9neon-linux-gnueabi.wandboard/oprofile-1.1.0/stage/machine/usr/src/linux/include/linux/perf_event.h usability... no
checking /mnt/xfs/devel/pil/oe-lite/tmp/work/machine/arm-cortexa9neon-linux-gnueabi.wandboard/oprofile-1.1.0/stage/machine/usr/src/linux/include/linux/perf_event.h presence... no
checking for /mnt/xfs/devel/pil/oe-lite/tmp/work/machine/arm-cortexa9neon-linux-gnueabi.wandboard/oprofile-1.1.0/stage/machine/usr/src/linux/include/linux/perf_event.h... no
checking kernel supports perf_events... unknown -- perf_event.h not found
ERROR: You requested to build oprofile with '--with-kernel=/mnt/xfs/devel/pil/oe-lite/tmp/work/machine/arm-cortexa9neon-linux-gnueabi.wandboard/oprofile-1.1.0/stage/machine/usr/src/linux',
but headers were not accessible at the given location.
Be sure you have run the following command from within your kernel source tree:
     make headers_install INSTALL_HDR_PATH=<kernel-hdrs-install-dir>

The problem is that the configure script tries to compile a file that
does a #include of the absolute path
</mnt/xfs/devel/pil/oe-lite/tmp/work/machine/arm-cortexa9neon-linux-gnueabi.wandboard/oprofile-1.1.0/stage/machine/usr/src/linux/include/linux/perf_event.h>,
and that file _does_ exist (contrary to the confusing output). However,
the test compile command fails to provide any -I flags, so the error
comes from linux/perf_event.h trying to include
uapi/linux/perf_event.h.

Instead of hard-coding the absolute path, the configure script should
try to compile

#include <linux/perf_event.h>

while passing "-I blabla/stage/machine/usr/src/linux/include" - that
should make the compiler find both the directly included file as well as
the files that includes.

For now, just set the priority to -1 so the 0.9.9 version gets used by
default. While trying to fix the problem above, one can use

  oe bake oprofile_1.1.0

to build this specific version.