gnupg: Fix mpi link problem in do_compile
Fix problem with linking in tools/, with lots of error messages like:

../mpi/libmpi.a(mpi-add.o): In function `mpi_add':
mpi-add.c:(.text+0x358): undefined reference to `mpihelp_sub_n'
mpi-add.c:(.text+0x49c): undefined reference to `mpihelp_add_n'
mpi-add.c:(.text+0x580): undefined reference to `mpihelp_sub_n'
mpi-add.c:(.text+0x5e8): undefined reference to `mpihelp_sub_n'
../mpi/libmpi.a(mpi-bit.o): In function `mpi_rshift':
mpi-bit.c:(.text+0x3ac): undefined reference to `mpihelp_rshift'

Signed-off-by: Esben Haabendal <esben.haabendal@prevas.dk>

(cherry picked from commit fb9182ed784cb6f4738fcae21de31ef921c9a876)