dbus-glib: Fix library linking in version 0.92
This resolves problems such as:

./.libs/libdbus-gtool.a(dbus-gparser.o): In function `locate_attributes.constprop.1':
dbus-gparser.c:(.text+0x208): undefined reference to `libintl_gettext'
./.libs/libdbus-gtool.a(dbus-gparser.o): In function `parser_start_element':
dbus-gparser.c:(.text+0x620): undefined reference to `libintl_gettext'

which breaks at least native builds on some machines.

Signed-off-by: Esben Haabendal <esben.haabendal@prevas.dk>